ALTER TABLE public.trusted_contacts ADD COLUMN relationship text NOT NULL DEFAULT '', ADD COLUMN phone text NOT NULL DEFAULT '', ADD COLUMN is_primary boolean NOT NULL DEFAULT false;
CREATE UNIQUE INDEX one_primary_contact_per_user ON public.trusted_contacts(user_id) WHERE is_primary;
ALTER TABLE public.emergency_events ADD COLUMN trigger text NOT NULL DEFAULT 'manual_sos', ADD COLUMN risk_score integer NOT NULL DEFAULT 100, ADD COLUMN status text NOT NULL DEFAULT 'emergency', ADD COLUMN user_response text, ADD COLUMN reasons jsonb NOT NULL DEFAULT '[]'::jsonb;
CREATE TABLE public.behavior_samples (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), activity text NOT NULL, speed double precision NOT NULL DEFAULT 0, duration_seconds integer NOT NULL DEFAULT 15, latitude double precision, longitude double precision, accuracy double precision, recorded_at timestamptz NOT NULL DEFAULT now(), accepted boolean NOT NULL DEFAULT true);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.behavior_samples TO authenticated;
GRANT ALL ON public.behavior_samples TO service_role;
ALTER TABLE public.behavior_samples ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own behavior" ON public.behavior_samples FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX behavior_user_time ON public.behavior_samples(user_id, recorded_at DESC);
CREATE TABLE public.behavior_baselines (user_id uuid PRIMARY KEY DEFAULT auth.uid(), baseline jsonb NOT NULL DEFAULT '{}'::jsonb, sample_count integer NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.behavior_baselines TO authenticated;
GRANT ALL ON public.behavior_baselines TO service_role;
ALTER TABLE public.behavior_baselines ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own baseline" ON public.behavior_baselines FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE TABLE public.risk_alerts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), sample_id uuid REFERENCES public.behavior_samples(id), score integer NOT NULL, level text NOT NULL, confidence integer NOT NULL, reasons jsonb NOT NULL DEFAULT '[]'::jsonb, latitude double precision, longitude double precision, created_at timestamptz NOT NULL DEFAULT now(), deadline timestamptz, status text NOT NULL DEFAULT 'observed', user_response text, emergency_event_id uuid REFERENCES public.emergency_events(id));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.risk_alerts TO authenticated;
GRANT ALL ON public.risk_alerts TO service_role;
ALTER TABLE public.risk_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own risk alerts" ON public.risk_alerts FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX alerts_user_time ON public.risk_alerts(user_id, created_at DESC);
CREATE UNIQUE INDEX one_pending_alert_per_user ON public.risk_alerts(user_id) WHERE status IN ('pending','escalating');