import { useEffect, useState } from 'react';
import { FlaskConical, Play, RotateCcw, ShieldCheck, Siren, ArrowRight, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SafetyShell, RiskBadge } from './safety-shell';
import { useSafety } from './safety-provider';
import { buildBaseline, scoreBehavior, type Sample } from '@/lib/behavior';
const steps = ['Normal Activity','Unusual Activity','High Risk','Safety Alert','No Response','Auto Escalation','Emergency','Resolution'];
function demoAssessment(step: number) {
  const samples: Sample[] = Array.from({length:120}, (_,i) => ({ activity: i%4 === 0 ? 'Stationary' : 'Walking', speed: i%4 === 0 ? 0 : 1.2, duration_seconds:15, latitude:22.5726, longitude:88.3639, recorded_at:`2026-10-${String(1+Math.floor(i/20)).padStart(2,'0')}T${i%2 === 0 ? '08' : '18'}:00:00.000Z` }));
  const sample: Sample = step === 0 ? { ...samples[1], activity:'Walking', speed:1.2, duration_seconds:15, latitude:22.5726, longitude:88.3639, recorded_at:'2026-10-07T08:00:00.000Z' } : step === 1 ? { ...samples[1], activity:'Walking', speed:1.2, duration_seconds:15, latitude:22.5726, longitude:88.3639, recorded_at:'2026-10-07T02:00:00.000Z' } : { activity:'Travelling', speed:10, duration_seconds:300, latitude:22.65, longitude:88.48, recorded_at:'2026-10-07T02:00:00.000Z' };
  return scoreBehavior(sample,buildBaseline(samples));
}
export function DemoView() {
  const safety = useSafety();
  useEffect(() => { safety.setMonitoring(false); }, [safety.setMonitoring]);
  const [step,setStep] = useState(-1), [remaining,setRemaining] = useState(30), [running,setRunning] = useState(false), [safe,setSafe] = useState(false);
  useEffect(() => { if (!running || step < 0 || step >= 7) return; const timer = setTimeout(() => { if (step === 3 && remaining > 1) setRemaining(v => v-1); else setStep(v => v+1); }, step === 3 ? 1000 : 2200); return () => clearTimeout(timer); },[running,step,remaining]);
  const risk = demoAssessment(Math.max(0,step));
  function reset() { setStep(-1); setRemaining(30); setRunning(false); setSafe(false); }
  return <SafetyShell title="Demo mode" eyebrow="SIMULATED SAFETY SCENARIO"><div className="demo-banner"><FlaskConical className="h-5 w-5" /><div><strong>DEMO MODE · SIMULATED DATA</strong><p>No real contacts are notified. No real activity, alerts or emergencies are saved.</p></div></div><div className="greeting-row"><p className="text-muted-foreground">A complete safety scenario using a labelled simulated baseline.</p><div className="flex gap-2"><Button variant="outline" onClick={reset}><RotateCcw className="h-4 w-4" />Reset</Button><Button disabled={running || step === 7} onClick={() => { setStep(0);setRemaining(30);setSafe(false);setRunning(true); }}><Play className="h-4 w-4" /> Run demo</Button></div></div><ol className="demo-timeline">{steps.map((text,i) => <li key={text} className={step === i ? 'current' : step > i ? 'complete' : ''}><span>{step > i ? <CheckCircle2 className="h-4 w-4" /> : String(i+1).padStart(2,'0')}</span><p>{text}</p></li>)}</ol><section className="demo-stage"><span className="eyebrow text-warning">DEMO / SIMULATED</span>{step < 0 ? <><FlaskConical className="demo-stage-icon" /><h2>Ready for a safety walkthrough</h2><p>Simulated baseline: 120 observations across six days in one usual location.</p></> : <><div className="flex items-center justify-center gap-3"><h2>{safe && step === 7 ? 'Alert resolved · I’m safe' : steps[step]}</h2>{step !== 7 && <RiskBadge level={risk.level} />}</div>{step < 4 && <div className="demo-score">{risk.score}<small>/100 · SIMULATED</small></div>}{step === 3 ? <><div className="countdown mx-auto">{remaining}<span>seconds</span></div><ul className="mx-auto my-5 max-w-md space-y-2 text-left text-sm text-muted-foreground">{risk.reasons.map(r => <li key={r}>• {r}</li>)}</ul><div className="flex flex-wrap justify-center gap-3"><Button variant="outline" onClick={() => { setStep(7);setSafe(true);setRunning(false); }}><ShieldCheck className="h-4 w-4" /> I'M SAFE</Button><Button onClick={() => setStep(6)}><Siren className="h-4 w-4" /> NEED HELP</Button></div></> : step >= 4 && step < 7 ? <><Siren className="demo-stage-icon text-destructive" /><p>{step === 4 ? 'No response received within 30 seconds.' : step === 5 ? 'Simulated automatic escalation triggered.' : 'SIMULATED emergency created. SIMULATED email notifications — no email sent.'}</p></> : step === 7 ? <><ShieldCheck className="demo-stage-icon text-success" /><p>SIMULATED event resolved. Your real safety history is unchanged.</p></> : <p>{risk.reasons.join(' ')}</p>}</>}{step >= 0 && step < 7 && step !== 3 && <Button variant="ghost" className="mt-5" onClick={() => setStep(v => v+1)}>Next stage <ArrowRight className="h-4 w-4" /></Button>}</section></SafetyShell>;
}
