import { Link, useRouterState, useNavigate } from '@tanstack/react-router';
import { useQueryClient } from '@tanstack/react-query';
import { ShieldCheck, LayoutDashboard, Brain, Activity, MapPin, Users, History, BookOpen, FlaskConical, LogOut, Siren, Radio } from 'lucide-react';
import { useEffect, useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { useSafety } from './safety-provider';
import { supabase } from '@/integrations/supabase/client';
const navigation = [
  { to: '/dashboard', title: 'Overview', icon: LayoutDashboard }, { to: '/digital-twin', title: 'Digital Twin', icon: Brain }, { to: '/monitoring', title: 'Monitoring', icon: Activity }, { to: '/location', title: 'Location', icon: MapPin }, { to: '/contacts', title: 'Trusted Contacts', icon: Users }, { to: '/history', title: 'Alert History', icon: History }, { to: '/safety-tips', title: 'Safety Tips', icon: BookOpen }, { to: '/demo', title: 'Demo Mode', icon: FlaskConical },
] as const;
export function SafetyShell({ title, eyebrow = 'YOUR PERSONAL SAFETY SPACE', children }: { title: string; eyebrow?: string; children: ReactNode }) {
  const s = useSafety(), qc = useQueryClient(), navigate = useNavigate(); const path = useRouterState({ select: v => v.location.pathname });
  const [sosVisible, setSosVisible] = useState(false);
  useEffect(() => { const button = document.querySelector('.dashboard-sos'); if (!button) { setSosVisible(false); return; } const observer = new IntersectionObserver(([entry]) => setSosVisible((entry?.intersectionRatio ?? 0) > 0.5), { threshold: [0, 0.5, 1] }); observer.observe(button); return () => observer.disconnect(); }, [path]);
  async function logout() { s.setMonitoring(false); await qc.cancelQueries(); qc.clear(); await supabase.auth.signOut(); await navigate({ to: '/auth', replace: true }); }
  return <div className="safety-app"><aside className="safety-sidebar"><Link to="/dashboard" className="brand"><span className="brand-mark"><ShieldCheck /></span><span>Guardian<span className="text-primary">AI</span><small>PERSONAL SAFETY</small></span></Link><p className="nav-label">WORKSPACE</p><nav>{navigation.map(({ to, title: text, icon: Icon }) => <Button key={to} variant="ghost" asChild className={`nav-item ${path === to ? 'active' : ''}`}><Link to={to}><Icon />{text}{path === to && <span className="nav-dot" />}</Link></Button>)}</nav><div className="sidebar-bottom"><div className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 text-success" /> Your data stays private</div><Button variant="ghost" onClick={logout} className="mt-4 w-full justify-start"><LogOut /> Log out</Button></div></aside><div className="safety-workspace"><header className="workspace-header"><div className="mobile-brand"><ShieldCheck className="text-primary" /> GuardianAI</div><div className="header-crumb hidden md:block">Workspace <span>/</span> <strong>{title}</strong></div><div className="flex items-center gap-4"><span className="monitor-status"><span className={s.monitoring ? 'status-dot live' : 'status-dot'} />{s.monitoring ? 'Monitoring active' : 'Monitoring off'}</span><span className="avatar">{(s.profile.data?.full_name || s.user?.email || 'G').slice(0, 1).toUpperCase()}</span></div></header><nav className="mobile-nav">{navigation.map(({ to, title: text, icon: Icon }) => <Button key={to} asChild variant="ghost" className={path === to ? 'active' : ''}><Link to={to}><Icon className="h-4 w-4" />{text}</Link></Button>)}<Button variant="ghost" onClick={logout}><LogOut className="h-4 w-4" />Log out</Button></nav><main className="workspace-main"><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div><span className="privacy-label"><ShieldCheck className="h-4 w-4" /> Protected workspace</span></div>{children}</main><footer className="workspace-footer"><span>GuardianAI · Personal safety, thoughtfully connected.</span><span>Not a replacement for local emergency services.</span></footer></div>{path !== "/demo" && !sosVisible && <Button className="mobile-sos" onClick={s.pressSos} disabled={s.busy}><Siren />{s.busy ? 'Sending SOS…' : 'Emergency SOS'}</Button>}</div>;
}
export function SectionHeading({ icon: Icon, title, note, action }: { icon: typeof Radio; title: string; note?: string; action?: ReactNode }) { return <div className="section-heading"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-muted-foreground" /><h2>{title}</h2>{note && <span className="section-note">{note}</span>}</div>{action}</div>; }
export function RiskBadge({ level }: { level: string }) { return <span className={`risk-badge risk-${level.toLowerCase()}`}><span className="status-dot" />{level}</span>; }
export function EmailStatus({ status, sent, failed }: { status: string; sent: number; failed: number }) { return <span className={status === 'sent' ? 'text-success' : status === 'pending' ? 'text-muted-foreground' : 'text-warning'}>{status === 'sent' ? `SMTP accepted · ${sent} contact(s)` : status === 'no_contacts' ? 'No enabled contacts' : status === 'pending' ? 'Sending…' : `${status} · ${sent} sent / ${failed} failed`}</span>; }
