import { useState } from 'react';
import { ArrowUpRight, Compass, Moon, Users, Globe, LifeBuoy, LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SafetyShell } from './safety-shell';
const categories = [
  { name: 'Travel Safety', icon: Compass, tips: [['Share your itinerary','Tell someone you trust where you’re going, your expected arrival time and how you’re travelling. Check in when you arrive.'],['Choose verified transport','Confirm the vehicle registration and driver before getting in. Wait in a well-lit public area and avoid sharing more personal information than necessary.'],['Keep an exit option','Charge your phone, keep a backup payment method and save an offline map before travelling somewhere unfamiliar.']] },
  { name: 'Night Travel', icon: Moon, tips: [['Plan a well-lit route','Prefer populated, well-lit streets even if the journey takes longer. Identify open shops or staffed places along the way.'],['Stay connected','Let a trusted person know your departure and arrival times. Keep your phone charged and avoid headphones that block surrounding sounds.'],['Wait somewhere staffed','If your ride is delayed, stay inside a staffed venue rather than alone at a quiet roadside.']] },
  { name: 'Public Places', icon: Users, tips: [['Notice exits and staff','When entering an unfamiliar venue, identify exits and staff members you could approach for support.'],['Keep drinks in view','Keep your drink with you and avoid accepting an unattended drink. If you feel unexpectedly unwell, tell a trusted person or staff immediately.'],['Trust your boundaries','You do not owe anyone personal details or continued conversation. Move to a staffed or populated place if you feel uncomfortable.']] },
  { name: 'Online Safety', icon: Globe, tips: [['Verify before trusting','Be cautious with urgent requests for money, codes or private photos. Confirm the person through a separate channel.'],['Meet safely','For first meetings with someone you met online, choose a public staffed place, arrange your own transport and tell a trusted contact.'],['Preserve evidence','If you receive threats, save messages and timestamps. Use platform reporting and blocking tools and seek local support if you feel unsafe.']] },
  { name: 'Emergency Preparedness', icon: LifeBuoy, tips: [['Save local emergency numbers','Know the emergency number for your current country. GuardianAI alerts trusted contacts; it does not contact emergency services.'],['Prepare your safety circle','Ask your trusted contacts to agree on what they should do if they receive an SOS email. Verify their email addresses together.'],['Keep essentials ready','Keep important medication, emergency contact details, a power bank and copies of essential documents accessible.']] },
  { name: 'Digital Privacy', icon: LockKeyhole, tips: [['Limit real-time sharing','Avoid publicly posting your live location, daily routine or travel plans. Share sensitive details only with people you trust.'],['Secure your accounts','Use unique strong passwords and multi-factor authentication where available. Review signed-in devices and remove unfamiliar sessions.'],['Review permissions','Check which apps can access your location, camera and microphone. Revoke access you do not need and keep your device updated.']] },
];
export function TipsView() { const [selected,setSelected] = useState('Travel Safety'); const category = categories.find(c => c.name === selected) ?? categories[0]; return <SafetyShell title="Safety tips" eyebrow="SMALL HABITS. STRONGER SAFETY."><div className="tip-categories">{categories.map(c => <Button key={c.name} variant={selected === c.name ? 'secondary' : 'ghost'} onClick={() => setSelected(c.name)}><c.icon className="h-4 w-4" />{c.name}</Button>)}</div>{category && <><div className="tips-heading"><category.icon className="h-6 w-6 text-chart-1" /><h2>{category.name}</h2><span>03 PRACTICAL TIPS</span></div><div className="tips-grid">{category.tips.map(([title,copy],i) => <article className="tip-card" key={title}><div className="flex justify-between text-muted-foreground"><span className="text-xs">0{i+1}</span><ShieldTip /></div><h3>{title}</h3><p>{copy}</p></article>)}</div></>}<p className="mt-8 text-sm text-muted-foreground">Safety is never solely your responsibility. If you are in immediate danger, contact local emergency services.</p></SafetyShell>; }
function ShieldTip() { return <ArrowUpRight className="h-4 w-4" />; }
